apiVersion: apps/v1
kind: Deployment
metadata:
  #creationTimestamp: null
  labels:
    app: cc-frontend
  name: cc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-frontend
  #strategy: {}
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: cc-frontend
    spec:
      containers:
      - image: kebidge/cc-frontend:latest
        name: cc-frontend
        env:
        - name: CC_BACKEND_ENDPOINT
          value: http://cc-backend:80/user/
        #resources: {}
#status: {}