apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cc-backend-db
  name: cc-backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-backend-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cc-backend-db
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: pwd
        - name: POSTGRES_USER
          value: kebidge
        - name: POSTGRES_DB
          value: cc-backend-db
        resources: {}
status: {}