apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cc-backend
  name: cc-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cc-backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cc-backend
    spec:
      containers:
      - image: kebidge/cc-backend:latest
        name: cc-backend
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: ${{secrets.POSTGRES_PASSWORD}}
        - name: SPRING_DATASOURCE_USERNAME
          value: ${{secrets.POSTGRES_USER}}
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://${{secrets.POSTGRES_DB}}:5432/${{secrets.POSTGRES_DB}}
        resources: {}
status: {}