apiVersion: v1
kind: Service
metadata:
  #creationTimestamp: null
  labels:
    app: cc-frontend
  name: cc-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
    name: http
  selector:
    app: cc-frontend
  type: LoadBalancer
#status:
  #loadBalancer: {}