apiVersion: v1
kind: Service
metadata:
  #creationTimestamp: null
  labels:
    app: cc-backend-db
  name: cc-backend-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: cc-backend-db
#status:
  #loadBalancer: {}