apiVersion: v1
kind: Service
metadata:
  #creationTimestamp: null
  labels:
    app: cc-backend
  name: cc-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    name: http
  selector:
    app: cc-backend
  type: LoadBalancer
#status:
 # loadBalancer: {}