# This is a basic workflow to help you get started with Actions

name: CC Backend Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This is the first job of the workflow called "build"
  build:
  
    # Name of Job
    name: Build Maven Project
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'
      
      # Build Maven Project and skip Tests
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      # Upload Target Directory as GitHub Artefact
      - name: Cache Target Directory
        uses: actions/upload-artifact@v3
        with:
          name: target-directory
          path: target
  
  # This is the second job of the workflow called "test"
  test:  
  
    name: Test Maven Project
    runs-on: ubuntu-latest
    needs: [build]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PMD Source Code Analyzer
        uses: sfdx-actions/setup-pmd@v1
    
      - name: Run PMD Source Code Analyzer
        run: pmd -d ./src -R pmd_ruleset.xml -f text
